### ISSUE TITLE
Not working on TestNet

### ISSUE THREAD

**Issue by railty** [AlgoDoggo/statelessAuth#1]
It works fine for MainNet. However once I switch to TestNet in my IOS Pera Wallet, (by setting->developer->node->TestNet), it gives this error:

Signing Error: Network mismatch between dApp and Wallet. For example, Wallet is connected to TestNet and dApp connected to MainNet (or vice versa).

It maybe a bug in Pera Wallet, as if I 

connector.on("connect", (error, payload) => {
  const { accounts, chainId } = payload.params[0];
  console.log("chainId=", chainId);
});

It always give 4160, MainNet.....

But I could be wrong...

**Comment by AlgoDoggo** [comment]
Yes I've hard coded mainnet in the draft Auth Transaction, mainly to avoid having to fetch suggested params:

https://github.com/AlgoDoggo/statelessAuth/blob/2198817b6445d0d79667c9e490418ee3e29634d6/src/helpers/draftAuthTx.js#L17

If you need this to work on testnet, you need to add a testnet prop to the function with the corresponding genesisID and genesisHash. Or fetch params from AlgoD, just remember to set fee to 0 and first and last valid to 10 or the back-end will reject.
